[project]
name = "agenda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "ortools>=9.14.6206",
    "pydantic>=2.11.9",
    "sqlalchemy>=2.0.43",
]

# [tool.uv] section removed: 'scripts' is not a valid field


